Walkover-Web-Solution/chatbot-ui

app/chatbot/layout.tsx
components/Grid/Grid.tsx
components/Interface-Chatbot/ChatbotHeader.tsx
components/Interface-Chatbot/Message.tsx
components/Interface-Table/InterfaceTable.tsx

Parsing error

---

components/Interface-Chatbot/ChatbotTextField.tsx
components/Interface-Chatbot/InterfaceChatbot.tsx
components/Interface-Chatbot/MessageList.tsx
components/Interface-Chatbot/StarterQuestions.tsx

text field center

---

components/Chatbot-Wrapper/ChatbotWrapper.tsx
components/Interface-Chatbot/InterfaceChatbot.tsx

version id null for histroy chatbot

version id null for histroy chatbot

---

app/globals.css
components/Interface-Chatbot/ChatbotDrawer.tsx

close drawer on subthread change for small screen

close drawer on subthread change for small screen

---

components/Interface-Chatbot/Message.tsx

show excuted function in dropdown

show excuted function in dropdown

---

components/Interface-Chatbot/ChatbotHeader.tsx

Reverts Walkover-Web-Solution/chatbot-ui#23

Revert "Feature -> Allow user to switch between bridges when allowBridgeSwitc…"

---

components/Interface-Chatbot/ChatbotHeader.tsx

Reverts Walkover-Web-Solution/chatbot-ui#24

Feature -> Allow user to switch between bridges when allowBridgeSwitch is true

---

components/Chatbot-Wrapper/ChatbotWrapper.tsx

version id null bug fix

---

app/rag/page.tsx

rag ui update testing

---

app/rag/page.tsx

rag ui update main

---

components/Interface-Chatbot/ChatbotDrawer.tsx
components/Interface-Chatbot/ChatbotHeader.tsx
components/Interface-Chatbot/ChatbotTextField.tsx
components/Interface-Chatbot/Interface-Markdown/InterfaceMarkdown.tsx
components/Interface-Chatbot/InterfaceChatbot.tsx
components/Interface-Chatbot/Message.tsx
components/Interface-Chatbot/MessageList.tsx
package.json
utils/appUtility.js

Bugfix for remark gfm plugin prod

Bugfix for remark gfm plugin prod

---

components/Chatbot/Chatbot.tsx
components/Chatbot/hooks/chatReducer.ts
components/Chatbot/hooks/chatTypes.ts
components/Chatbot/hooks/useChatActions.ts
components/Interface-Chatbot/ChatbotDrawer.tsx
components/Interface-Chatbot/MessageList.tsx
components/Interface-Chatbot/MoveToDownButton.tsx

pagination bug fix

---

components/Chatbot/Chatbot.tsx
components/Chatbot/hooks/HelloVoiceService.ts
components/Hello/RenderHelloInteractiveMessage.tsx
components/Hello/callUI.tsx
components/Interface-Chatbot/ChatbotHeader.tsx
components/Interface-Chatbot/Messages/Message.tsx
components/Interface-Chatbot/Messages/MessageList.tsx
components/Interface-Chatbot/MoveToDownButton.tsx
package.json
public/chat-widget-dev.js
public/chat-widget-local.js
public/chat-widget-prodtesing.js
public/chat-widget-style.css
public/chat-widget.js

1. Header UI
2. bottom padding reducer from messagelist
3. Reducer the min-size for user message
4. Move to down arrow acc. to theme
5.

Minor fixex

---

components/Chatbot/Chatbot.tsx
components/Chatbot/hooks/useHelloIntegration.ts
components/Hello/RenderHelloInteractiveMessage.tsx
components/Interface-Chatbot/Messages/Message.tsx
hooks/socketEventHandler.ts
package.json
utils/dataConvertWrappers/makeGenericDataFormatUtility.tsx
utils/utilities.js

showing time on assistant and user message
handle text field in center and user message timestamp
dont show border in interactive section type
showing textfield in center when there is not a single chat

Version 2 v2

---

app/rag/page.tsx

udpate event for rag emebed

---

app/rag/page.tsx

rag name update event prod

---

components/Chatbot/Chatbot.tsx
components/Chatbot/hooks/useHelloIntegration.ts
components/Interface-Chatbot/ChatbotDrawer.tsx
components/Interface-Chatbot/Messages/Message.tsx
components/Interface-Chatbot/Messages/MessageList.tsx
hooks/notifications/notificationSocket.ts
hooks/notifications/notificationSocketEventHandler.tsx
hooks/notifications/notificationSocketManager.ts
public/chat-widget-dev.js
public/chat-widget-local.js
public/chat-widget-prodtesing.js
public/chat-widget-style.css
public/chat-widget.js
utils/emitEventsToParent/emitEventsToParent.tsx

push notifications handling for popup and message type
opening push notification in iframe in message type popup and in shadow dom for message type message

push notification hanlding

---

components/Chatbot/hooks/useChatActions.ts
components/Chatbot/hooks/useRtlayerEventManager.tsx
components/Interface-Chatbot/ChatbotDrawer.tsx
components/Interface-Chatbot/ChatbotHeader.tsx
store/interface/interfaceReducer.ts

Sub thread readable

---

components/Grid/Grid.tsx
components/Grid/Viewonlygrid.tsx
components/Interface-Button/InterfaceButton.tsx
components/Interface-Chatbot/Messages/Message.tsx
utils/ChatbotUtility.ts

Action to chatbot

---

app/rag/page.tsx

added id in the event to parent main

added id in the event to parent main

---

app/rag/page.tsx

rag event bug fix main

---

app/rag/page.tsx
public/rag-dev.js
public/rag-local.js
public/rag-prod.js

rag ui and script update

---

app/rag/page.tsx
public/rag-dev.js
public/rag-local.js
public/rag-prod.js

sending loaded event to praent rag

sending loaded event to praent rag

---

app/rag/page.tsx
public/rag-dev.js
public/rag-local.js
public/rag-prod.js

Rag script update main

---

public/rag-dev.js
public/rag-local.js
public/rag-prod.js

conflicting ifram parent id with chatbot script bug fix

conflicting ifram parent id with chatbot script bug fix

---

public/rag-dev.js
public/rag-local.js
public/rag-prod.js

conflicting ifram parent id with chatbot script bug fix main

conflicting iframe parent id with chatbot script bug fix main

---

app/rag/page.tsx
public/rag-dev.js
public/rag-local.js
public/rag-prod.js
public/rag.css

rag script update with css

---

config/api.ts

sending not null data in subscribe api

sending not null data in subscribe api

---

app/rag/page.tsx
components/Chatbot/hooks/chatReducer.ts
components/Interface-Chatbot/Messages/Message.tsx
hoc/addUrlDataHoc.tsx
hooks/HELLO/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
hooks/notifications/notificationSocketManager.ts
hooks/socketManager.js
public/chatbot-dev.js
public/chatbot-local.js
public/chatbot.js

hotfix event issue

---

config/api.ts

removing null data from subscribea api

removing null data from subscribea api

---

components/Interface-Chatbot/ChatbotDrawer.tsx
components/Interface-Chatbot/ChatbotHeader.tsx
hooks/GTWY/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
types/appInfo/appInfoReduxType.ts

hideclosebutton and hideFullScreenbutton tabwise data store

hideclosebutton and hideFullScreenbutton tabwise data store

---

app/rag/page.tsx

rag drive bug fix testing

---

components/Chatbot/hooks/useChatActions.ts
config/api.ts

add slugname in get all thread api

add slugname in get all thread api

---

components/Chatbot/hooks/useChatActions.ts
config/api.ts

slugname in get all thread api

slugname in get all thread api

---

app/rag/page.tsx
components/Chatbot/Chatbot.tsx
components/Chatbot/hooks/HelloVoiceService.ts
components/Chatbot/hooks/useHelloEffects.ts
components/Chatbot/hooks/useReduxEffects.ts
components/Chatbot/hooks/useReduxManagement.ts
components/FormComponent.tsx
components/Interface-Chatbot/CallButton.tsx
components/Interface-Chatbot/ChatbotDrawer.tsx
components/Interface-Chatbot/ChatbotHeader.tsx
components/Interface-Chatbot/ChatbotTextField.tsx
components/Interface-Chatbot/InterfaceChatbot.tsx
config/helloApi.ts
hooks/HELLO/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
package.json
public/chat-widget-dev.js
public/chat-widget-local.js
public/chat-widget-prodtesing.js
public/chat-widget-style.css
public/chat-widget.js
public/urlMonitor.js
store/draftData/draftDataSlice.ts
store/hello/helloReducer.ts
store/hello/helloSlice.ts
store/interface/interfaceSlice.ts
types/hello/HelloReduxType.ts
types/interface/InterfaceReduxType.ts
types/reduxCore.ts
utils/emitEventsToParent/emitEventsToParent.tsx

Testing sync with test 14 jul gtwy

Testing sync with test 14 jul gtwy

---

public/rag-dev.js
public/rag-local.js
public/rag-prod.js

show document list only when parent id or default open is true

show document list only when parent id or default open is true

---

components/Chatbot/hooks/useChatActions.ts

version is setting string instead of null fixed

version is setting string instead of null fixed

---

public/chatbot-dev.js
public/chatbot-local.js
public/chatbot.js

Main = solve the Iconflickerig issue by asyn-await

Main = solve the Iconflickerig issue by asyn-await

---

components/Interface-Chatbot/Messages/AssistantMessage.tsx

multiple image genration main

---

components/Chatbot/hooks/useHelloEffects.ts
components/Chatbot/hooks/useHelloIntegration.ts
components/Interface-Chatbot/ChatbotHeader.tsx
components/Interface-Chatbot/ChatbotTextField.tsx
components/Interface-Chatbot/Messages/AssistantMessage.tsx
components/Interface-Chatbot/Messages/HumanOrBotMessage.tsx
components/Interface-Chatbot/Messages/ImageWithFallback.tsx
components/Interface-Chatbot/Messages/MessageTime.tsx
components/Interface-Chatbot/Messages/UserMessage.tsx
hooks/HELLO/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
public/chat-widget-dev.js
public/chat-widget-local.js
public/chat-widget-prodtesing.js
public/chat-widget-style.css
public/chat-widget.js
public/urlMonitor.js

testing sync with test 8 aug

---

components/Interface-Chatbot/ChatbotTextField.tsx

Removed slider from options

---

store/index.js

500 route issue
